### ISSUE TITLE
Map <extref> to <ref>

### ISSUE THREAD

**Issue by noahgh221** [NCSU-Libraries/archivesspace#1]
`<extref>` is deprecated in EAD3, map `<extref>` to `<ref>` and preserve attributes.

Link to extref handling in EAD2002 to EAD3 stylesheet: https://github.com/SAA-SDT/EAD2002toEAD3/blob/master/xslt/EAD2002ToEAD3schema.xsl#L2132``

**Comment by trevorthornton** [comment]
Is this in reference to the exporter itself or in cleaning up mixed content in notes as they exist in the data?

**Comment by noahgh221** [comment]
Cleaning up mixed content in notes.  Can the exporter just change any occurrence of <extref> to <ref>?

**Comment by noahgh221** [comment]
Confirmed fix
