### ISSUE TITLE
Typo? <dimension> should be <dimensions> (plural)

### ISSUE THREAD

**Issue by noahgh221** [NCSU-Libraries/archivesspace#10]
Here's where the error appears:
```
 <physdescstructured coverage="whole" physdescstructuredtype="spaceoccupied">
                  <quantity>1</quantity>
                  <unittype>items</unittype>
                  <dimension>2.5 cm diameter</dimension>
                </physdescstructured>
```

**Comment by noahgh221** [comment]
@trevorthornton , Now `<dimensions>` is missing from exports entirely.

**Comment by noahgh221** [comment]
`<dimensions>` still not appearing in component list (`<dsc>`)

**Comment by trevorthornton** [comment]
@noahgh221 - I can't reproduce this problem. Can you send me an EAD (2002) export for a resource where this is happening so that I can import into my test instance?

**Comment by trevorthornton** [comment]
@noahgh221 found the problem - fix is committed and will be in the next build

**Comment by noahgh221** [comment]
confirmed fix
