### ISSUE TITLE
<title> requires child <part> element

### ISSUE THREAD

**Issue by noahgh221** [NCSU-Libraries/archivesspace#4]
Supply child element `<part>` of `<title>` in mixed content fields.

See: http://loc.gov/ead/EAD3taglib/index.html#elem-title

**Comment by trevorthornton** [comment]
Also applies to corpname, famname, function, genreform, geogname, name, occupation, persname, subject. Fix should handle all of these.

**Comment by noahgh221** [comment]
Confirmed fix
