### ISSUE TITLE
Remove camel case from all attribute values

### ISSUE THREAD

**Issue by noahgh221** [NCSU-Libraries/archivesspace#5]
Camel case is not supported in EAD3.  See preface to tag library: http://loc.gov/ead/EAD3taglib/#d0e115

Example: `dao/@actuate` values should be all lowercase: onload, onrequst (not onLoad or onRequest).

**Comment by trevorthornton** [comment]
Not sure if this is an issue with any attributes other than @actuate, but to be safe I'll downcase all attributes with closed value lists.

**Comment by noahgh221** [comment]
@trevorthornton , I'm still seeing camelcase values of @actuate (onLoad and onRequest) in my exports.

```
 <dao actuate="onRequest" daotype="unknown"
              href="http://library.duke.edu/digitalcollections/russianposters_rpcps02012/"
              linktitle="Proletarians of the world unite" localtype="web-resource-link" show="new">
              <descriptivenote>
                <p>Proletarians of the world unite</p>
              </descriptivenote>
            </dao>
```

**Comment by trevorthornton** [comment]
Is that `<dao>` included in a note or is it being generated from a digitalObject?

**Comment by noahgh221** [comment]
That `<dao>` was generated from a digital object.

![image](https://user-images.githubusercontent.com/7328518/29225839-cf367d72-7e9d-11e7-8d77-e85aa8bf162c.png)

**Comment by noahgh221** [comment]
confirmed fix.
